---
title: "bankChurn"
output: pdf_document
---


```{r}
#necessary libraries
library(tidyverse)
library(caret)
library(glmnet)
library(leaps)
library(MASS)
library(dplyr)
library(mgcv)
library(ggplot2)
library(magrittr)
library(gridExtra)
library(ggplot2)
library(hrbrthemes)
library(corrplot)
library(ggcorrplot)
library(scales)
library(ggmap)
library(car)
source("C:\\Users\\jonni\\Desktop\\Data Science Material\\Advanced Data Analysis\\code\\Confusion.R")
```

```{r}
#loading dataset and performing cleaning 
bankingFullData = read.csv("C:\\Users\\jonni\\Downloads\\BankChurners.csv\\BankChurners.csv")

supremeData <- bankingFullData[, 2:21]
binnedData <- as.data.frame(matrix(nrow=10127,ncol=4))

#since this feature can be composed of other features, this will be done to reduce memory
supremeData$Avg_Open_To_Buy <- (supremeData$Credit_Limit - supremeData$Total_Revolving_Bal)

#conditional statements to replace unknown with median
supremeData$Income_Category <- ifelse(supremeData$Income_Category == "Unknown", "$40K - $60K", supremeData$Income_Category)
supremeData$Education_Level <- ifelse(supremeData$Education_Level == "Unknown", "College", supremeData$Education_Level)
supremeData$Marital_Status <- ifelse(supremeData$Marital_Status == "Unknown", "Married", supremeData$Marital_Status)

#simplifying results
supremeData$Attrition_Flag[supremeData$Attrition_Flag=="Existing Customer"]<-"NoChurn"
supremeData$Attrition_Flag[supremeData$Attrition_Flag=="Attrited Customer"]<-"Churn"
supremeData$Attrition_Flag <- as.factor(supremeData$Attrition_Flag)
#using the factor function to provide order and numeric mapping
supremeData$Gender <- as.factor(supremeData$Gender)
supremeData$Income_Category <- factor(supremeData$Income_Category, order = TRUE, levels = c( "Less than $40K", "$40K - $60K", "$60K - $80K", "$80K - $120K", "$120K +"))
supremeData$Education_Level <- factor(supremeData$Education_Level, order = TRUE, levels = c("Uneducated", "High School", "College", "Graduate", "Post-Graduate", "Doctorate"))
supremeData$Card_Category <- factor(supremeData$Card_Category, order = TRUE, levels = c("Blue", "Silver", "Gold", "Platinum"))
supremeData$Marital_Status <- factor(supremeData$Marital_Status, order = TRUE, levels = c("Single","Married","Divorced"))

#below is general format of cleaning data
#supremeData$test <- as.integer(supremeData$Education_Level)
#supremeData$test <- ifelse(supremeData$test == 1, 4, supremeData$test)
#supremeData$test <- factor(supremeData$test, order = TRUE, levels = c(2, 3, 4, 5, 6))


#below data were binned according to supervised discretion to better visualize data and underlying knowledge
binnedData$avgOpenBinned <- cut(round(supremeData$Avg_Open_To_Buy), c(-Inf, 3500, 10000, 20000, Inf), labels = c("$0-$3.5k", "$3.5-$10k", "$10-$20k", "$20k-$35k"))
binnedData$creditBinned <- cut(round(supremeData$Credit_Limit), c(-Inf, 2555, 8632,20000, Inf), labels=c("Q1, 0-$2.555k", "Mean (2.55-$8.632k)", "8.632k-$20k","20k-$35k"))
binnedData$transAmtBinned <- cut(supremeData$Total_Trans_Amt, c(-Inf, 2156, 4404, 10000, Inf), labels = c("Q1(0-$2156)", "Mean ($2157-$4404)", "Mean to 10k", "10k-35k"))
binnedData$avgUtilBinned <- cut(supremeData$Avg_Open_To_Buy, c(-Inf, 1324, 7469, 9859, Inf), labels = c("first quartile(0-$1324)", "1q to Mean ($1324-$7469)", "Mean to Q3 (7.4k-$9.8k", "7469k-$35k"))
#the above binned data is to get a better visualization on histograms/bar plots to distinguish variable distribution

#different subsets organized here
numericData <- supremeData[, c(2,4,9,10,11,12,13,14,15,16,17,18,19,20)]
categorical <- supremeData[, c(1,3,5,6,7,8)]
```

```{r}
#Using visualization techniques to better understand relationships in data
histPlots <- supremeData %>% keep(is.numeric) %>% gather() %>% 
  ggplot() + 
  geom_histogram(mapping = aes(x=value,fill=key), color="purple",bins=25) + 
  facet_wrap(~ key, scales = "free") +      
  theme_minimal() +
  theme(legend.position = 'none')

histPlots

barPlots <- categorical %>% gather() %>% 
  ggplot() + 
  geom_bar(mapping = aes(x=value,fill=key), color="purple") + 
  facet_wrap(~ key, scales = "free") +      
  theme_minimal() +
  theme(legend.position = 'none')

barPlots2 <- binnedData %>% gather() %>% 
  ggplot() + 
  geom_bar(mapping = aes(x=value,fill=key), color="purple") + 
  facet_wrap(~ key, scales = "free") +      
  theme_minimal() +
  theme(legend.position = 'none')

barPlots
barPlots2
```
```{r}
#regression techniques

df <- supremeData

set.seed(1972)

# Splitting data set to train and test set
## 75% of the sample size
smp_size <- floor(0.75 * nrow(df))
train_ind <- sample(seq_len(nrow(df)), size = smp_size)
train <- df[train_ind, ]
test <- df[-train_ind, ]
```

```{r}
#Model 1 - Logistic Regression-k-fold cross-validation
# Specify/train logistic regression model using k-folds (n=10) cross validation framework
#set your control specs
ctrl <-trainControl(method = "cv", savePredictions = "all", number = 10, classProbs = T)
m1<- train(Attrition_Flag~.,data = train, method="glm", family=binomial, trControl=ctrl)
summary(m1)
#prediction and diagnostics below

m1.pred = predict(m1, newdata=test)
m1_cm <- confusionMatrix(data=m1.pred, test$Attrition_Flag)
m1_cm

varImp(m1)

m1.2<- train(Attrition_Flag ~ Gender + Dependent_count + Marital_Status + Income_Category + Total_Relationship_Count + Months_Inactive_12_mon + Contacts_Count_12_mon + Credit_Limit + Total_Revolving_Bal + Total_Trans_Amt + Total_Trans_Ct + Total_Ct_Chng_Q4_Q1, data = train, method="glm", family=binomial(link = 'logit'), trControl=ctrl)
m2.pred = predict(m1, newdata=test)
m2_cm <- confusionMatrix(data=m1.pred, test$Attrition_Flag)
m2_cm
summary(m1.2)
```

```{r}
# MODEL 2 - LASSO Regression analysis-k-fold cross validation
set.seed(1972)

glm_model <- glm(Attrition_Flag ~ ., data = train, family = binomial)

summary(glm_model)
glm_prob <- predict.glm(glm_model,test[,-1], type = "response")
contrasts(test$Attrition_Flag)
glm_predict <- rep("Churn",nrow(test))
glm_predict[glm_prob>.5] <- "NoChurn"
table(pred=glm_predict,true=test$Attrition_Flag)

#convert training data to matrix format
x <- model.matrix(Attrition_Flag~.,train)
#convert class to numerical variable
y <- ifelse(train$Attrition_Flag=="NoChurn",1,0)

cv.out.lasso <- cv.glmnet(x,y,alpha=1,family="binomial",type.measure = "mse" )
plot(cv.out.lasso)

#min value of lambda
lambda_min_lasso <- cv.out.lasso$lambda.min
log(lambda_min_lasso)

#best value of lambda
lambda_1se_lasso <- cv.out.lasso$lambda.1se
log(lambda_1se_lasso)

#regression coefficients
coef(cv.out.lasso,s=lambda_1se_lasso)

#get test data
x_test_lasso <- model.matrix(Attrition_Flag~.,test)

#predict class, type=”class”
lasso_prob <- predict(cv.out.lasso,newx = x_test_lasso,s=lambda_1se_lasso,type="response")

#translate probabilities to predictions
lasso_predict <- rep("Churn",nrow(test))
lasso_predict[lasso_prob>.5] <- "NoChurn"

#confusion matrix
table(pred=lasso_predict,true=test$Attrition_Flag)

#accuracy
mean(lasso_predict==test$Attrition_Flag)
```

```{r}
# MODEL 3 - Ridge regression analysis-k-fold cross validation
set.seed(1972)

#cv.out <- cv.glmnet(x,y,alpha=1,family="binomial",type.measure = "mse" )
cv.out.ridge <- cv.glmnet(x,y,alpha=0,family="binomial",type.measure = "mse" )
plot(cv.out.ridge)

#min value of lambda
lambda_min_ridge <- cv.out.ridge$lambda.min
log(lambda_min_ridge)

#best value of lambda
lambda_1se_ridge <- cv.out.ridge$lambda.1se
log(lambda_1se_ridge)

#regression coefficients
coef(cv.out.ridge,s=lambda_1se_ridge)

#get test data
x_test_ridge <- model.matrix(Attrition_Flag~.,test)

#predict class, type=”class”
ridge_prob <- predict(cv.out.ridge,newx = x_test_ridge,s=lambda_1se_ridge,type="response")

#translate probabilities to predictions
ridge_predict <- rep("Churn",nrow(test))
ridge_predict[ridge_prob>.5] <- "NoChurn"

#confusion matrix
table(pred=ridge_predict,true=test$Attrition_Flag)

#accuracy
mean(ridge_predict==test$Attrition_Flag)
```

```{r}
#PCA
cor(numericData)
#removed correlated vars
numericData <- numericData[-c(3,12,14)]

p = prcomp(numericData, scale=T)
summary(p)
p
plot(p$x[,1], p$x[, 2])
plot(p)
p$rotation
biplot(p, expand=1.5, xlim =c(-.05, .02), ylim=c(-.05,.1))

tester <- numericData[,c(3,5,8)]
p2 = prcomp(tester, scale=T)
summary(p2)
p2
biplot(p2,expand=2, xlim =c(-.08, .05), ylim=c(-.08,.05))

```

```{r}
#check correlation in the data
#existing = 0, churned/attrited = 1
boxplot(Total_Trans_Amt ~ Attrition_Flag, data=supremeData, col='light blue')
boxplot(Total_Revolving_Bal ~ Attrition_Flag, data=supremeData, col='light blue')
boxplot(Credit_Limit ~ Attrition_Flag, data=supremeData, col='light blue')
boxplot(Avg_Utilization_Ratio ~ Attrition_Flag, data=supremeData, col='light blue')



model.LDA <- lda(Attrition_Flag ~ ., data = train)
plot(model.LDA)
p = predict(model.LDA, newdata = train[,c(2:20)])
#the accuracy of this model is 90%
confusionMatrix(train$Attrition_Flag, p$class)
plot(p$x, col=train$Attrition_Flag, pch=16)
#this histogram shows that  churn customers are to the left of zero
ldahist(p$x[,1], g=train$Attrition_Flag)

print(predict(model.LDA, test[1:5,]))
#in this example the 4th row is being predicted as a churn, lets print it out to observe a profile
print(test[4,])


#testing set
p2 = predict(model.LDA, newdata = test[,c(2:20)])
confusionMatrix(test$Attrition_Flag, p2$class)
plot(p2$x, col=test$Attrition_Flag, pch=16)
ldahist(p2$x[,1], g=test$Attrition_Flag)
print(model.LDA$scaling)


model.LDA <- lda(Attrition_Flag ~ ., data = train)
plot(model.LDA)
p = predict(model.LDA, newdata = train[,c(2:20)])
#the accuracy of this model is 90%
confusionMatrix(train$Attrition_Flag, p$class)
plot(p$x, col=train$Attrition_Flag, pch=16)
#this histogram shows that  churn customers are to the left of zero
ldahist(p$x[,1], g=train$Attrition_Flag)

print(predict(model.LDA, test[1:5,]))
#in this example the 4th row is being predicted as a churn, lets print it out to observe a profile
print(test[4,])


#testing set
p2 = predict(model.LDA, newdata = test[,c(2:20)])
confusionMatrix(test$Attrition_Flag, p2$class)
plot(p2$x, col=test$Attrition_Flag, pch=16)
ldahist(p2$x[,1], g=test$Attrition_Flag)
print(model.LDA$scaling)


```
































